# Project: ErrorTesting
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = mainTesting.o $(RES)
LINKOBJ  = mainTesting.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib"  
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = ErrorTesting.exe
CXXFLAGS = $(CXXINCS)   -g -masm=intel
CFLAGS = $(INCS)   -g -masm=intel
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before ErrorTesting.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "ErrorTesting.exe" $(LIBS)

mainTesting.o: mainTesting.cpp
	$(CPP) -c mainTesting.cpp -o mainTesting.o $(CXXFLAGS)
